name: oppi
services:
  path_planning:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - "9002:9002"
    container_name: ws_server
    volumes:
      - .:/ws
